// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  fragrance_list: dynamic(() => import("./FragranceList")),
  hero: dynamic(() => import("./Hero")),
  product_freature: dynamic(() => import("./ProductFreature")),
  scroll_text: dynamic(() => import("./ScrollText")),
};
